### PR TITLE
Namespaces

### PR DESCRIPTION
**Pull request by hazbo**
I had a play around with adding namespaces to your class, and adding a composer file in there, (currently not on packagist) it does mean that it only now supports >= PHP 5.3.Hopefully this would mean that it is now a lot easier for people to use your API by just pulling the component down using composer.

I have tried to make the code in the class itself more PSR-1/2ish and generally have generally tidied it up in there a little bit.

### CODE REVIEW

**Comment by hazbo** [comment]
I didn't notice until straight after this will affect the tests. Not much though, all that needs doing is to load the class in differently and all should be good.

**Comment by zimbatm** [comment]
Hi @hazbo, that looks really cool.

Since there is just a single class wouldn't it make more sense to just keep it top-level and avoid loosing PHP5.1 compatibility ? I'm not super familiar with PHP so pardon me if that seems obvious.

Also sorry for the lack of response, apparently I wasn't subscribed to this repo so I didn't get the PR notification.

**Comment by hazbo** [comment]
Hello!
As it stands, yeah having it top level would make more sense for a single class, and we would lose PHP5.1 with the use of namespaces.
But ideally, it would be nice to see a lot of the code in that class split up into more relevant classes, so a class to deal with making requests or dealing with responses etc... It's not necessary for it to work, but would be nicer code and a bit easier to maintain.

Thanks for getting back to me though! :)

**Comment by zimbatm** [comment]
Yeah finally :)

What about the composer.json, would it be possible to benefit from it without the namespace ? I'll keep the namespace idea in mind the day we make more substantial improvements to the library.

**Comment by hazbo** [comment]
Yeah I'm pretty sure you can use composer to autoload without the use of namespaces. I didn't submit it to packagist, I thought it'd make more sense if one of you guys wanted to do that.

If you were to keep `Panda.php` top level, I believe you'd have to change the `psr-0` line in `composer.json` from:

```
"psr-0": { "Panda\\Component": "src" }
```

To

```
"psr-0": { "Panda": "" }
```

`Panda` referring to the name of the class so it can be auto-loaded, and the empty string, because it's in the top level. If you were to put it in a directory named `src` for example, it would be:

```
"psr-0": { "Panda": "src/" }
```

I haven't tested it with an empty string, but it should work.

**Pull request closed without merging**
